//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJob2.AzureWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="AzureWebService.SampleWebServiceSoap")]
    public interface SampleWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/VerifyEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebJob2.AzureWebService.UserModel VerifyEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/VerifyEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<WebJob2.AzureWebService.UserModel> VerifyEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DownloadSubject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebJob2.AzureWebService.SubjectModel[] DownloadSubject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DownloadSubject", ReplyAction="*")]
        System.Threading.Tasks.Task<WebJob2.AzureWebService.SubjectModel[]> DownloadSubjectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DownloadBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebJob2.AzureWebService.BookModel[] DownloadBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DownloadBook", ReplyAction="*")]
        System.Threading.Tasks.Task<WebJob2.AzureWebService.BookModel[]> DownloadBookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DownloadAuthor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebJob2.AzureWebService.AuthorModel[] DownloadAuthor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DownloadAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<WebJob2.AzureWebService.AuthorModel[]> DownloadAuthorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DownloadBookAuthors", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebJob2.AzureWebService.BookAuthorModel[] DownloadBookAuthors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DownloadBookAuthors", ReplyAction="*")]
        System.Threading.Tasks.Task<WebJob2.AzureWebService.BookAuthorModel[]> DownloadBookAuthorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DownloadPublisher", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebJob2.AzureWebService.PublisherModel[] DownloadPublisher();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DownloadPublisher", ReplyAction="*")]
        System.Threading.Tasks.Task<WebJob2.AzureWebService.PublisherModel[]> DownloadPublisherAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ViewReservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebJob2.AzureWebService.ReservationModel[] ViewReservation(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ViewReservation", ReplyAction="*")]
        System.Threading.Tasks.Task<WebJob2.AzureWebService.ReservationModel[]> ViewReservationAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ReserveBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReserveBook(string userId, string bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ReserveBook", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReserveBookAsync(string userId, string bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/CancelReservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CancelReservation(string reservationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/CancelReservation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CancelReservationAsync(string reservationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ViewComment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebJob2.AzureWebService.CommentModel[] ViewComment(string bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ViewComment", ReplyAction="*")]
        System.Threading.Tasks.Task<WebJob2.AzureWebService.CommentModel[]> ViewCommentAsync(string bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebJob2.AzureWebService.UserModel GetUser(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WebJob2.AzureWebService.UserModel> GetUserAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebJob2.AzureWebService.BookModel GetBook(string bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetBook", ReplyAction="*")]
        System.Threading.Tasks.Task<WebJob2.AzureWebService.BookModel> GetBookAsync(string bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/AddNewComment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddNewComment(string userId, string bookId, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/AddNewComment", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddNewCommentAsync(string userId, string bookId, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/RateBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RateBook(string userId, string bookId, int rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/RateBook", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RateBookAsync(string userId, string bookId, int rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/NotifyBookDeadline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebJob2.AzureWebService.BookLogsModel[] NotifyBookDeadline();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/NotifyBookDeadline", ReplyAction="*")]
        System.Threading.Tasks.Task<WebJob2.AzureWebService.BookLogsModel[]> NotifyBookDeadlineAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class UserModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Guid studentIdField;
        
        private System.Nullable<System.Guid> imageIdField;
        
        private string emailField;
        
        private string passwordField;
        
        private string passwordSaltField;
        
        private string pincodeField;
        
        private string pincodeSaltField;
        
        private string roleField;
        
        private string secretQuestionField;
        
        private string secretAnswerField;
        
        private bool deletedField;
        
        private bool statusField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private System.Nullable<System.DateTime> updatedAtField;
        
        private StudentModel studentField;
        
        private ImageModel imageField;
        
        private CommentModel[] commentsField;
        
        private BookLogsModel[] bookLogsField;
        
        private RatingModel[] ratingsField;
        
        public UserModel() {
            this.deletedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid StudentId {
            get {
                return this.studentIdField;
            }
            set {
                this.studentIdField = value;
                this.RaisePropertyChanged("StudentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.Guid> ImageId {
            get {
                return this.imageIdField;
            }
            set {
                this.imageIdField = value;
                this.RaisePropertyChanged("ImageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PasswordSalt {
            get {
                return this.passwordSaltField;
            }
            set {
                this.passwordSaltField = value;
                this.RaisePropertyChanged("PasswordSalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Pincode {
            get {
                return this.pincodeField;
            }
            set {
                this.pincodeField = value;
                this.RaisePropertyChanged("Pincode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PincodeSalt {
            get {
                return this.pincodeSaltField;
            }
            set {
                this.pincodeSaltField = value;
                this.RaisePropertyChanged("PincodeSalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SecretQuestion {
            get {
                return this.secretQuestionField;
            }
            set {
                this.secretQuestionField = value;
                this.RaisePropertyChanged("SecretQuestion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SecretAnswer {
            get {
                return this.secretAnswerField;
            }
            set {
                this.secretAnswerField = value;
                this.RaisePropertyChanged("SecretAnswer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
                this.RaisePropertyChanged("UpdatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public StudentModel Student {
            get {
                return this.studentField;
            }
            set {
                this.studentField = value;
                this.RaisePropertyChanged("Student");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public ImageModel Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        public CommentModel[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        public BookLogsModel[] BookLogs {
            get {
                return this.bookLogsField;
            }
            set {
                this.bookLogsField = value;
                this.RaisePropertyChanged("BookLogs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=19)]
        public RatingModel[] Ratings {
            get {
                return this.ratingsField;
            }
            set {
                this.ratingsField = value;
                this.RaisePropertyChanged("Ratings");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class StudentModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Guid sectionIdField;
        
        private System.Nullable<System.Guid> studentAddressIdField;
        
        private string firstNameField;
        
        private string middleInitialField;
        
        private string lastNameField;
        
        private string genderField;
        
        private System.Nullable<System.DateTime> birthdayField;
        
        private string contactNumberField;
        
        private bool statusField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private System.Nullable<System.DateTime> updatedAtField;
        
        private SectionsModel sectionField;
        
        private StudentAddressModel studentAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid SectionId {
            get {
                return this.sectionIdField;
            }
            set {
                this.sectionIdField = value;
                this.RaisePropertyChanged("SectionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.Guid> StudentAddressId {
            get {
                return this.studentAddressIdField;
            }
            set {
                this.studentAddressIdField = value;
                this.RaisePropertyChanged("StudentAddressId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MiddleInitial {
            get {
                return this.middleInitialField;
            }
            set {
                this.middleInitialField = value;
                this.RaisePropertyChanged("MiddleInitial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("Birthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ContactNumber {
            get {
                return this.contactNumberField;
            }
            set {
                this.contactNumberField = value;
                this.RaisePropertyChanged("ContactNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
                this.RaisePropertyChanged("UpdatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public SectionsModel Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
                this.RaisePropertyChanged("Section");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public StudentAddressModel StudentAddress {
            get {
                return this.studentAddressField;
            }
            set {
                this.studentAddressField = value;
                this.RaisePropertyChanged("StudentAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class SectionsModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Guid gradeIdField;
        
        private System.Nullable<System.Guid> imageIdField;
        
        private string sectionField;
        
        private bool deletedField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private System.Nullable<System.DateTime> updatedAtField;
        
        private GradesModel gradeField;
        
        private ImageModel imageField;
        
        public SectionsModel() {
            this.deletedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid GradeId {
            get {
                return this.gradeIdField;
            }
            set {
                this.gradeIdField = value;
                this.RaisePropertyChanged("GradeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.Guid> ImageId {
            get {
                return this.imageIdField;
            }
            set {
                this.imageIdField = value;
                this.RaisePropertyChanged("ImageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
                this.RaisePropertyChanged("Section");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
                this.RaisePropertyChanged("UpdatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public GradesModel Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
                this.RaisePropertyChanged("Grade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public ImageModel Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class GradesModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Nullable<System.Guid> imageIdField;
        
        private string gradeField;
        
        private bool deleteField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private System.Nullable<System.DateTime> updatedAtField;
        
        private SectionsModel[] sectionsField;
        
        private ImageModel imageField;
        
        public GradesModel() {
            this.deleteField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.Guid> ImageId {
            get {
                return this.imageIdField;
            }
            set {
                this.imageIdField = value;
                this.RaisePropertyChanged("ImageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
                this.RaisePropertyChanged("Grade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
                this.RaisePropertyChanged("Delete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
                this.RaisePropertyChanged("UpdatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public SectionsModel[] Sections {
            get {
                return this.sectionsField;
            }
            set {
                this.sectionsField = value;
                this.RaisePropertyChanged("Sections");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ImageModel Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ImageModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid imageIdField;
        
        private string pathField;
        
        private string nameField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private System.Nullable<System.DateTime> updatedAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ImageId {
            get {
                return this.imageIdField;
            }
            set {
                this.imageIdField = value;
                this.RaisePropertyChanged("ImageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("Path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
                this.RaisePropertyChanged("UpdatedAt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class BookLogsModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Guid userIdField;
        
        private System.Guid bookIdField;
        
        private bool returnField;
        
        private bool bookStatusField;
        
        private string messageLogField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private System.DateTime deadlineField;
        
        private System.Nullable<System.DateTime> updatedAtField;
        
        private UserModel userField;
        
        private BookModel bookField;
        
        public BookLogsModel() {
            this.returnField = false;
            this.bookStatusField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
                this.RaisePropertyChanged("BookId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool BookStatus {
            get {
                return this.bookStatusField;
            }
            set {
                this.bookStatusField = value;
                this.RaisePropertyChanged("BookStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MessageLog {
            get {
                return this.messageLogField;
            }
            set {
                this.messageLogField = value;
                this.RaisePropertyChanged("MessageLog");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime Deadline {
            get {
                return this.deadlineField;
            }
            set {
                this.deadlineField = value;
                this.RaisePropertyChanged("Deadline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
                this.RaisePropertyChanged("UpdatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public UserModel User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public BookModel Book {
            get {
                return this.bookField;
            }
            set {
                this.bookField = value;
                this.RaisePropertyChanged("Book");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class BookModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Guid subjectIdField;
        
        private System.Guid publisherIdField;
        
        private string iSBNField;
        
        private string titleField;
        
        private string synopsisField;
        
        private System.DateTime copyrightField;
        
        private string volumeField;
        
        private int noOfPagesField;
        
        private double priceField;
        
        private int quantityField;
        
        private bool borrowField;
        
        private bool deleteField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private System.Nullable<System.DateTime> updatedAtField;
        
        private BookAuthorModel[] booksAuthorsField;
        
        private SubjectModel subjectField;
        
        private PublisherModel publisherField;
        
        private CommentModel[] commentsField;
        
        private RatingModel[] ratingsField;
        
        private ReservationModel[] reservationsField;
        
        private BookLogsModel[] bookLogsField;
        
        public BookModel() {
            this.deleteField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid SubjectId {
            get {
                return this.subjectIdField;
            }
            set {
                this.subjectIdField = value;
                this.RaisePropertyChanged("SubjectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid PublisherId {
            get {
                return this.publisherIdField;
            }
            set {
                this.publisherIdField = value;
                this.RaisePropertyChanged("PublisherId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
                this.RaisePropertyChanged("ISBN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Synopsis {
            get {
                return this.synopsisField;
            }
            set {
                this.synopsisField = value;
                this.RaisePropertyChanged("Synopsis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime Copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
                this.RaisePropertyChanged("Copyright");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
                this.RaisePropertyChanged("Volume");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int NoOfPages {
            get {
                return this.noOfPagesField;
            }
            set {
                this.noOfPagesField = value;
                this.RaisePropertyChanged("NoOfPages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Borrow {
            get {
                return this.borrowField;
            }
            set {
                this.borrowField = value;
                this.RaisePropertyChanged("Borrow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
                this.RaisePropertyChanged("Delete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
                this.RaisePropertyChanged("UpdatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        public BookAuthorModel[] BooksAuthors {
            get {
                return this.booksAuthorsField;
            }
            set {
                this.booksAuthorsField = value;
                this.RaisePropertyChanged("BooksAuthors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public SubjectModel Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public PublisherModel Publisher {
            get {
                return this.publisherField;
            }
            set {
                this.publisherField = value;
                this.RaisePropertyChanged("Publisher");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        public CommentModel[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=19)]
        public RatingModel[] Ratings {
            get {
                return this.ratingsField;
            }
            set {
                this.ratingsField = value;
                this.RaisePropertyChanged("Ratings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        public ReservationModel[] Reservations {
            get {
                return this.reservationsField;
            }
            set {
                this.reservationsField = value;
                this.RaisePropertyChanged("Reservations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=21)]
        public BookLogsModel[] BookLogs {
            get {
                return this.bookLogsField;
            }
            set {
                this.bookLogsField = value;
                this.RaisePropertyChanged("BookLogs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class BookAuthorModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Guid bookIdField;
        
        private System.Guid authorIdField;
        
        private bool deletedField;
        
        private BookModel bookField;
        
        private AuthorModel authorField;
        
        public BookAuthorModel() {
            this.deletedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
                this.RaisePropertyChanged("BookId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid AuthorId {
            get {
                return this.authorIdField;
            }
            set {
                this.authorIdField = value;
                this.RaisePropertyChanged("AuthorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public BookModel Book {
            get {
                return this.bookField;
            }
            set {
                this.bookField = value;
                this.RaisePropertyChanged("Book");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public AuthorModel Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("Author");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class AuthorModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string middleInitialField;
        
        private bool deleteField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private System.Nullable<System.DateTime> updatedAtField;
        
        private BookAuthorModel[] booksAuthorsField;
        
        public AuthorModel() {
            this.deleteField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MiddleInitial {
            get {
                return this.middleInitialField;
            }
            set {
                this.middleInitialField = value;
                this.RaisePropertyChanged("MiddleInitial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
                this.RaisePropertyChanged("Delete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
                this.RaisePropertyChanged("UpdatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public BookAuthorModel[] BooksAuthors {
            get {
                return this.booksAuthorsField;
            }
            set {
                this.booksAuthorsField = value;
                this.RaisePropertyChanged("BooksAuthors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class SubjectModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private int callNoField;
        
        private string subjectField;
        
        private BookModel[] booksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CallNo {
            get {
                return this.callNoField;
            }
            set {
                this.callNoField = value;
                this.RaisePropertyChanged("CallNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public BookModel[] Books {
            get {
                return this.booksField;
            }
            set {
                this.booksField = value;
                this.RaisePropertyChanged("Books");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class PublisherModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private string publisherNameField;
        
        private bool deleteField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private System.Nullable<System.DateTime> updatedAtField;
        
        private BookModel[] bookField;
        
        public PublisherModel() {
            this.deleteField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PublisherName {
            get {
                return this.publisherNameField;
            }
            set {
                this.publisherNameField = value;
                this.RaisePropertyChanged("PublisherName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
                this.RaisePropertyChanged("Delete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
                this.RaisePropertyChanged("UpdatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public BookModel[] Book {
            get {
                return this.bookField;
            }
            set {
                this.bookField = value;
                this.RaisePropertyChanged("Book");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class CommentModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Guid userIdField;
        
        private System.Guid bookIdField;
        
        private string commentField;
        
        private bool deleteField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private System.Nullable<System.DateTime> updatedAtField;
        
        private UserModel userField;
        
        private BookModel bookField;
        
        public CommentModel() {
            this.deleteField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
                this.RaisePropertyChanged("BookId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
                this.RaisePropertyChanged("Delete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
                this.RaisePropertyChanged("UpdatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public UserModel User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public BookModel Book {
            get {
                return this.bookField;
            }
            set {
                this.bookField = value;
                this.RaisePropertyChanged("Book");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class RatingModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Guid userIdField;
        
        private System.Guid bookIdField;
        
        private int rateField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private UserModel userField;
        
        private BookModel bookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
                this.RaisePropertyChanged("BookId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("Rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public UserModel User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public BookModel Book {
            get {
                return this.bookField;
            }
            set {
                this.bookField = value;
                this.RaisePropertyChanged("Book");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ReservationModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Guid userIdField;
        
        private System.Guid bookIdField;
        
        private bool deleteField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private System.Nullable<System.DateTime> updatedAtField;
        
        private UserModel userField;
        
        private BookModel bookField;
        
        public ReservationModel() {
            this.deleteField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
                this.RaisePropertyChanged("BookId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
                this.RaisePropertyChanged("Delete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
                this.RaisePropertyChanged("UpdatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public UserModel User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public BookModel Book {
            get {
                return this.bookField;
            }
            set {
                this.bookField = value;
                this.RaisePropertyChanged("Book");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class StudentAddressModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private int zipCodeField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string countryField;
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private System.Nullable<System.DateTime> updatedAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("CreatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
                this.RaisePropertyChanged("UpdatedAt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SampleWebServiceSoapChannel : WebJob2.AzureWebService.SampleWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleWebServiceSoapClient : System.ServiceModel.ClientBase<WebJob2.AzureWebService.SampleWebServiceSoap>, WebJob2.AzureWebService.SampleWebServiceSoap {
        
        public SampleWebServiceSoapClient() {
        }
        
        public SampleWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebJob2.AzureWebService.UserModel VerifyEmail(string email) {
            return base.Channel.VerifyEmail(email);
        }
        
        public System.Threading.Tasks.Task<WebJob2.AzureWebService.UserModel> VerifyEmailAsync(string email) {
            return base.Channel.VerifyEmailAsync(email);
        }
        
        public WebJob2.AzureWebService.SubjectModel[] DownloadSubject() {
            return base.Channel.DownloadSubject();
        }
        
        public System.Threading.Tasks.Task<WebJob2.AzureWebService.SubjectModel[]> DownloadSubjectAsync() {
            return base.Channel.DownloadSubjectAsync();
        }
        
        public WebJob2.AzureWebService.BookModel[] DownloadBook() {
            return base.Channel.DownloadBook();
        }
        
        public System.Threading.Tasks.Task<WebJob2.AzureWebService.BookModel[]> DownloadBookAsync() {
            return base.Channel.DownloadBookAsync();
        }
        
        public WebJob2.AzureWebService.AuthorModel[] DownloadAuthor() {
            return base.Channel.DownloadAuthor();
        }
        
        public System.Threading.Tasks.Task<WebJob2.AzureWebService.AuthorModel[]> DownloadAuthorAsync() {
            return base.Channel.DownloadAuthorAsync();
        }
        
        public WebJob2.AzureWebService.BookAuthorModel[] DownloadBookAuthors() {
            return base.Channel.DownloadBookAuthors();
        }
        
        public System.Threading.Tasks.Task<WebJob2.AzureWebService.BookAuthorModel[]> DownloadBookAuthorsAsync() {
            return base.Channel.DownloadBookAuthorsAsync();
        }
        
        public WebJob2.AzureWebService.PublisherModel[] DownloadPublisher() {
            return base.Channel.DownloadPublisher();
        }
        
        public System.Threading.Tasks.Task<WebJob2.AzureWebService.PublisherModel[]> DownloadPublisherAsync() {
            return base.Channel.DownloadPublisherAsync();
        }
        
        public WebJob2.AzureWebService.ReservationModel[] ViewReservation(string userId) {
            return base.Channel.ViewReservation(userId);
        }
        
        public System.Threading.Tasks.Task<WebJob2.AzureWebService.ReservationModel[]> ViewReservationAsync(string userId) {
            return base.Channel.ViewReservationAsync(userId);
        }
        
        public string ReserveBook(string userId, string bookId) {
            return base.Channel.ReserveBook(userId, bookId);
        }
        
        public System.Threading.Tasks.Task<string> ReserveBookAsync(string userId, string bookId) {
            return base.Channel.ReserveBookAsync(userId, bookId);
        }
        
        public string CancelReservation(string reservationId) {
            return base.Channel.CancelReservation(reservationId);
        }
        
        public System.Threading.Tasks.Task<string> CancelReservationAsync(string reservationId) {
            return base.Channel.CancelReservationAsync(reservationId);
        }
        
        public WebJob2.AzureWebService.CommentModel[] ViewComment(string bookId) {
            return base.Channel.ViewComment(bookId);
        }
        
        public System.Threading.Tasks.Task<WebJob2.AzureWebService.CommentModel[]> ViewCommentAsync(string bookId) {
            return base.Channel.ViewCommentAsync(bookId);
        }
        
        public WebJob2.AzureWebService.UserModel GetUser(string userId) {
            return base.Channel.GetUser(userId);
        }
        
        public System.Threading.Tasks.Task<WebJob2.AzureWebService.UserModel> GetUserAsync(string userId) {
            return base.Channel.GetUserAsync(userId);
        }
        
        public WebJob2.AzureWebService.BookModel GetBook(string bookId) {
            return base.Channel.GetBook(bookId);
        }
        
        public System.Threading.Tasks.Task<WebJob2.AzureWebService.BookModel> GetBookAsync(string bookId) {
            return base.Channel.GetBookAsync(bookId);
        }
        
        public string AddNewComment(string userId, string bookId, string comment) {
            return base.Channel.AddNewComment(userId, bookId, comment);
        }
        
        public System.Threading.Tasks.Task<string> AddNewCommentAsync(string userId, string bookId, string comment) {
            return base.Channel.AddNewCommentAsync(userId, bookId, comment);
        }
        
        public string RateBook(string userId, string bookId, int rate) {
            return base.Channel.RateBook(userId, bookId, rate);
        }
        
        public System.Threading.Tasks.Task<string> RateBookAsync(string userId, string bookId, int rate) {
            return base.Channel.RateBookAsync(userId, bookId, rate);
        }
        
        public WebJob2.AzureWebService.BookLogsModel[] NotifyBookDeadline() {
            return base.Channel.NotifyBookDeadline();
        }
        
        public System.Threading.Tasks.Task<WebJob2.AzureWebService.BookLogsModel[]> NotifyBookDeadlineAsync() {
            return base.Channel.NotifyBookDeadlineAsync();
        }
    }
}
